sudo: false
cache: bundler
language: ruby
env:
  - SECRET_KEY_BASE="$(bundle exec rake secret)"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
before_install: gem update --remote bundler
install:
  - bundle install --retry=3 --without development
script:
  - export SECRET_KEY_BASE="$(bundle exec rake secret)"
  - bundle exec rake