sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>

postgresql: &postgresql
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  min_messages: ERROR
  reconnect: false

default: &default
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
